variables:
  MAC_RUNNER_IMAGE: 'macOS-10.14'
  NODE_VERSION: '10.x'
  XCODE_VERSION: '11.3.1'

trigger:
  branches:
    include:
      - master

stages:
- stage: Tests
  jobs:
  - job: UiTests
    pool:
      vmImage: '$(MAC_RUNNER_IMAGE)'
    steps:
    - task: NodeTool@0
      displayName: 'Set Node version $(NODE_VERSION)'
      inputs:
        versionSpec: $(NODE_VERSION)
    - script: npm install
      displayName: 'NPM Install'
      workingDirectory: '$(Build.SourcesDirectory)/demo'
    - script: sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
      displayName: 'Select xcode $(XCODE_VERSION)'
    - script: ./run_ios_debug.sh
      displayName: 'Run tests'
      workingDirectory: '$(Build.SourcesDirectory)/demo'
    - publish: $(Build.SourcesDirectory)/demo/snapshots/ios
      condition: failed()
      artifact: screenshots_android
      displayName: 'Results'
